services:
  algo:
    image: nav-simulator:latest
    container_name: algo
    command: ["/usr/local/bin/algo_node", "--sub-addr", "tcp://0.0.0.0:8080", "--pub-addr", "tcp://0.0.0.0:8081"]
    ports:
      - "8080:8080" #<host port>:<container port>
      - "8081:8081"

  sat1:
    image: nav-simulator:latest
    container_name: sat1
    command: ["/usr/local/bin/sat_node", "--id", "1", "--phase-angle", "0.0", "--pub-addr", "tcp://algo:8080"]
    depends_on:
      - algo

  sat2:
    image: nav-simulator:latest
    container_name: sat2
    command: ["/usr/local/bin/sat_node", "--id", "2", "--phase-angle", "30.0", "--pub-addr", "tcp://algo:8080"]
    depends_on:
      - algo

  sat3:
    image: nav-simulator:latest
    container_name: sat3
    command: ["/usr/local/bin/sat_node", "--id", "3", "--phase-angle", "60.0", "--pub-addr", "tcp://algo:8080"]
    depends_on:
      - algo

  vehicle:
    image: nav-simulator:latest
    container_name: vehicle
    command: ["/usr/local/bin/vehicle_node", "--velocity", "35.0", "--efficiency", "7.0", "--fuel", "55.0", "--pub-addr", "tcp://algo:8080"]
    depends_on:
      - algo